[package]
name = "krpc-mars-terraformer"
version = "0.8.0"
authors = ["cahu"]
license = "GPL-3.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.94"
thiserror = "1.0.39"
heck = "0.4.1"
tera = "1.17.1"
